SECTOR_DEFINITIONS = {
    "TELECOM": ["BHARTIARTL"],
    "METAL": [
        "ADANIENT", "APLAPOLLO", "BHARATFORG", "COALINDIA",
        "HINDALCO", "HINDZINC", "JSWSTEEL", "JINDALSTEL", "NMDC",
        "NATIONALUM", "SAIL", "TATASTEEL", "VEDL",
    ],
    "REALTY": [
        "PHOENIXLTD", "GODREJPROP", "LODHA", "OBEROIRLTY", "DLF",
        "PRESTIGE", "NBCC", "RVNL",
    ],
    "ENERGY": [
        "RELIANCE", "ONGC", "IOC", "BPCL", "OIL", "NTPC", "POWERGRID",
        "POWERINDIA", "TATAPOWER", "JSWENERGY", "ADANIGREEN", "ADANIENSOL", "ADANIPOWER",
        "NHPC", "IREDA", "SUZLON", "INOXWIND", "WAAREEENER", "PREMIERENE",
        "PETRONET", "GAIL", "HINDPETRO",
    ],
    "AUTO": [
        "BOSCHLTD", "TIINDIA", "HEROMOTOCO", "M&M", "EICHERMOT",
        "BAJAJ-AUTO", "ASHOKLEY", "MARUTI", "TVSMOTOR", "MOTHERSON",
        "SONACOMS", "UNOMINDA", "TMPV", "HYUNDAI", "AMBER",
    ],
    "IT": [
        "INFY", "TCS", "HCLTECH", "WIPRO", "TECHM", "LTM", "MPHASIS",
        "KPITTECH", "COFORGE", "PERSISTENT", "TATAELXSI", "OFSS", "CAMS",
        "NAUKRI", "KAYNES",
    ],
    "PHARMA": [
        "CIPLA", "ALKEM", "BIOCON", "DRREDDY", "MANKIND", "TORNTPHARM",
        "ZYDUSLIFE", "DIVISLAB", "LUPIN", "LAURUSLABS", "FORTIS", "AUROPHARMA",
        "GLENMARK", "SUNPHARMA", "MAXHEALTH", "APOLLOHOSP",
    ],
    "FMCG": [
        "HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "DABUR", "MARICO",
        "COLPAL", "GODREJCP", "TATACONSUM", "PATANJALI", "UNITDSPR", "RADICO",
        "VBL", "DMART", "NYKAA", "ETERNAL", "SWIGGY", "TITAN", "TRENT",
        "VMM", "KALYANKJIL", "JUBLFOOD", "ASIANPAINT",
    ],
    "CEMENT": [
        "ULTRACEMCO", "SHREECEM", "AMBUJACEM", "DALBHARAT", "GRASIM", "ASTRAL",
        "PIDILITIND", "SUPREMEIND",
    ],
    "FINSERVICE": [
        "BAJFINANCE", "BAJAJFINSV", "BAJAJHLDNG", "ICICIPRULI", "ICICIGI", "SBILIFE",
        "HDFCLIFE", "LICI", "LICHSGFIN", "PNBHOUSING", "MUTHOOTFIN", "MANAPPURAM",
        "CHOLAFIN", "PFC", "RECLTD", "MOTILALOFS", "HDFCAMC", "360ONE", "KFINTECH",
        "PAYTM", "POLICYBZR", "SBICARD", "JIOFIN", "SHRIRAMFIN", "ANGELONE",
        "BSE", "CDSL", "MCX", "IRFC",
    ],
    "BANK": [
        "HDFCBANK", "ICICIBANK", "AXISBANK", "KOTAKBANK", "IDFCFIRSTB", "FEDERALBNK",
        "INDUSINDBK", "AUBANK", "BANDHANBNK", "RBLBANK",
    ],
    "PSUBANK": [
        "SBIN", "PNB", "BANKBARODA", "CANBK", "UNIONBANK", "BANKINDIA", "INDIANB",
    ],
    "DURABLES": [
        "INDUSTOWER", "HAVELLS", "KEI", "POLYCAB", "CROMPTON", "VOLTAS", "PGEL",
        "DIXON", "SRF",
    ],
    "LOGISTICS": [
        "CONCOR", "DELHIVERY", "INDIGO", "INDHOTEL", "IRCTC", "BLUESTARCO",
        "GMRAIRPORT", "PAGEIND", "UPL", "ADANIPORTS",
    ],
    "DEFENCE": [
        "ABB", "BEL", "BDL", "BHEL", "CGPOWER", "CUMMINSIND", "HAL", "LT",
        "MAZDOCK", "COCHINSHIP", "SIEMENS", "SOLARINDS",
    ],
    "NIFTY_50": [
        "ADANIENT", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE",
        "BAJAJFINSV", "BEL", "BHARTIARTL", "BPCL", "CIPLA", "COALINDIA", "DRREDDY",
        "EICHERMOT", "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HINDALCO",
        "HINDUNILVR", "ICICIBANK", "INFY", "INDIGO", "ITC", "JIOFIN", "JSWSTEEL",
        "KOTAKBANK", "LT", "M&M", "MARUTI", "MAXHEALTH", "NESTLEIND", "NTPC", "ONGC",
        "POWERGRID", "RELIANCE", "SBILIFE", "SHRIRAMFIN", "SBIN", "SUNPHARMA", "TCS",
        "TATACONSUM", "TATASTEEL", "TECHM", "TITAN", "TRENT", "ULTRACEMCO", "WIPRO",
        "TMPV", "ETERNAL",
    ],
}

ALL_SYMBOLS = sorted({symbol for symbols in SECTOR_DEFINITIONS.values() for symbol in symbols})
